/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Service.EmployeeService;
import java.awt.Component;
import java.awt.Window;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.text.MessageFormat;
import java.util.Properties;
import java.util.Random;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.standard.OrientationRequested;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import model.Employee;

/**
 *
 * @author GENTIL
 */
public class RegistrationForm extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationForm
     */
    public RegistrationForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchId = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        EmpId = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        fnameTxt = new javax.swing.JTextField();
        lnameTxt = new javax.swing.JTextField();
        phoneTxt = new javax.swing.JTextField();
        s = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        roleTxt = new javax.swing.JTextField();
        genderComboTxt = new javax.swing.JComboBox<String>();
        passwdTxt = new javax.swing.JPasswordField();
        usernameTxt = new javax.swing.JTextField();
        empIdTxt = new javax.swing.JLabel();
        registerBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchId.setBackground(new java.awt.Color(0, 102, 102));
        searchId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        searchId.setForeground(new java.awt.Color(0, 51, 255));
        searchId.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Employee Registration");
        searchId.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 480, -1));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 255), java.awt.Color.white));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EmpId.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        EmpId.setForeground(new java.awt.Color(255, 255, 255));
        EmpId.setText("Employee ID :");
        jPanel2.add(EmpId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("First Name");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 142, -1, -1));

        jLabel17.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Last Name");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 187, -1, -1));

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Gender");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 234, -1, -1));

        phone.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        phone.setForeground(new java.awt.Color(255, 255, 255));
        phone.setText("Phone No: ");
        jPanel2.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 284, -1, -1));

        jLabel20.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Email");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 344, -1, -1));

        fnameTxt.setBackground(new java.awt.Color(0, 102, 102));
        fnameTxt.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(fnameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 138, 182, -1));

        lnameTxt.setBackground(new java.awt.Color(0, 102, 102));
        lnameTxt.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lnameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 183, 182, -1));

        phoneTxt.setBackground(new java.awt.Color(0, 102, 102));
        phoneTxt.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(phoneTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 280, 182, -1));

        s.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        s.setForeground(new java.awt.Color(255, 255, 255));
        s.setText("Password");
        jPanel2.add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 402, -1, -1));

        jLabel22.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Role");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 470, -1, -1));

        roleTxt.setBackground(new java.awt.Color(0, 102, 102));
        roleTxt.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(roleTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 466, 182, -1));

        genderComboTxt.setBackground(new java.awt.Color(0, 102, 102));
        genderComboTxt.setForeground(new java.awt.Color(0, 102, 102));
        genderComboTxt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "F", "M" }));
        jPanel2.add(genderComboTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 230, 79, -1));

        passwdTxt.setBackground(new java.awt.Color(0, 102, 102));
        passwdTxt.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(passwdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 398, 182, -1));

        usernameTxt.setBackground(new java.awt.Color(0, 102, 102));
        usernameTxt.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(usernameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 340, 182, -1));

        empIdTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        empIdTxt.setForeground(new java.awt.Color(255, 255, 255));
        empIdTxt.setText("XXXXX");
        jPanel2.add(empIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 120, -1));

        registerBtn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(204, 51, 0));
        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        jPanel2.add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 330, -1));

        resetBtn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        resetBtn.setForeground(new java.awt.Color(204, 51, 0));
        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        jPanel2.add(resetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 330, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Have An Account ?");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 610, -1, -1));

        jButton1.setText("Sign In");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 600, 120, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Images/Icons/icons8-exit-50 (1).png"))); // NOI18N
        jLabel3.setText("Exit");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 770, 120, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Images/Icons/icons8-airplane-64.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Images/Icons/icons8-exit-50 (1).png"))); // NOI18N
        jLabel4.setText("Exit");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 770, 120, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SignUp Here");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        searchId.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 440, 660));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Images/3aba6c7ffe9b19107a01690375a556d7.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        searchId.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 570, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Images/Icons/icons8-airplane-64.png"))); // NOI18N
        searchId.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1058, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchId, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 774, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchId, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        try {
            Registry theregistry = LocateRegistry.getRegistry("127.0.0.1", 6000);

            EmployeeService service = (EmployeeService) theregistry.lookup("employee");
            empIdTxt.setText(service.AutoEmployee_id());
        } catch (Exception e) {
        }

        fnameTxt.setText("");
        lnameTxt.setText("");
        genderComboTxt.setSelectedIndex(-1);
        phoneTxt.setText("");
        usernameTxt.setText("");
        passwdTxt.setText("");
        roleTxt.setText("");
        registerBtn.setEnabled(true);
    }//GEN-LAST:event_resetBtnActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        if (fnameTxt.getText().trim().isEmpty() || lnameTxt.getText().trim().isEmpty() || passwdTxt.getPassword().length == 0
            || phoneTxt.getText().trim().isEmpty() || usernameTxt.getText().trim().isEmpty() || roleTxt.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Fill All Fields", "Empty Fields", JOptionPane.ERROR_MESSAGE);
            resetBtnActionPerformed(evt);
        } else {
            // Initialize the Employee object
            Employee emp = new Employee();

            // Generate and send OTP
            String correctOtp = generateOtp();
            String userEmail = usernameTxt.getText();
            sendOtp(userEmail, correctOtp);
            JOptionPane.showMessageDialog(this, "OTP sent to " + userEmail);

            // Prompt the user to enter the OTP
            String enteredOtp = JOptionPane.showInputDialog(this, "Enter the OTP sent to your email:", "OTP Verification", JOptionPane.PLAIN_MESSAGE);

            // Validate the OTP
            if (correctOtp.equals(enteredOtp)) {
                try {
                    // Connect to the registry and lookup the service
                    Registry theregistry = LocateRegistry.getRegistry("127.0.0.1", 6000);
                    EmployeeService service = (EmployeeService) theregistry.lookup("employee");

                    // Set the Employee details
                    emp.setEmp_id(service.AutoEmployee_id());
                    emp.setFname(fnameTxt.getText());
                    emp.setLname(lnameTxt.getText());
                    emp.setGender(genderComboTxt.getSelectedItem().toString());
                    emp.setPhoneNo(phoneTxt.getText());
                    emp.setUsername(usernameTxt.getText());
                    emp.setPassword(new String(passwdTxt.getPassword()));
                    emp.setRole(roleTxt.getText());

                    // Register the employee
                    String feedback = service.registerEmployee(emp);

                    // Provide feedback to the user
                    JOptionPane.showMessageDialog(this, feedback, "Feedback", JOptionPane.INFORMATION_MESSAGE);

                    // Update the table and reset fields

                    resetBtnActionPerformed(evt);
                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this, "An error occurred during registration. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Invalid OTP. Please try again.", "Invalid OTP", JOptionPane.ERROR_MESSAGE);
            }
        }
        }

        private String generateOtp() {
            // Generate a 6-digit numeric OTP
            Random random = new Random();
            int otpValue = 100000 + random.nextInt(900000);
            return String.valueOf(otpValue);
        }

        private void sendOtp(String recipientEmail, String otp) {
            // Set up SMTP properties
            Properties properties = new Properties();
            properties.put("mail.smtp.host", "smtp.gmail.com");
            properties.put("mail.smtp.port", "587");
            properties.put("mail.smtp.auth", "true");
            properties.put("mail.smtp.starttls.enable", "true");

            // Authentication with Gmail
            String fromEmail = "gentilniyo@gmail.com"; // Your Gmail address
            String appPassword = "lcmg ijnq qjod yyjs"; // Your App Password

            // Create a session with authentication
            Session session = Session.getInstance(properties, new Authenticator() {
                @Override
                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication(fromEmail, appPassword);
                }
            });

            try {
                // Create the email message
                Message message = new MimeMessage(session);
                message.setFrom(new InternetAddress(fromEmail));
                message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(recipientEmail));
                message.setSubject("Your OTP");
                message.setText("Your one-time password (OTP) from Gentil is: " + otp);

                // Send the email
                Transport.send(message);
                System.out.println("OTP sent successfully to " + recipientEmail);

            } catch (MessagingException ex) {
                ex.printStackTrace();
                System.out.println("Error sending OTP to " + recipientEmail + ": " + ex.getMessage());
                JOptionPane.showMessageDialog(null, "Failed to send OTP. Please try again later.", "Error", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_registerBtnActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Confirm Exit", JOptionPane.YES_NO_OPTION);

        // Check the user's response
        if (response == JOptionPane.YES_OPTION) {
            // If the user clicked "Yes", open the login page
            LoginPage loginPage = new LoginPage();
            loginPage.setVisible(true);

            // Optionally, close the current window
            Component source = (Component) evt.getSource();
            Window currentWindow = SwingUtilities.getWindowAncestor(source);
            if (currentWindow != null) {
                currentWindow.dispose();
            }
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Confirm Exit", JOptionPane.YES_NO_OPTION);

        // Check the user's response
        if (response == JOptionPane.YES_OPTION) {
            // If the user clicked "Yes", open the login page
            LoginPage loginPage = new LoginPage();
            loginPage.setVisible(true);

            // Optionally, close the current window
            Component source = (Component) evt.getSource();
            Window currentWindow = SwingUtilities.getWindowAncestor(source);
            if (currentWindow != null) {
                currentWindow.dispose();
            }
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();                
        LoginPage loginPage = new LoginPage();
        loginPage.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmpId;
    private javax.swing.JLabel empIdTxt;
    private javax.swing.JTextField fnameTxt;
    private javax.swing.JComboBox<String> genderComboTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lnameTxt;
    private javax.swing.JPasswordField passwdTxt;
    private javax.swing.JLabel phone;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JButton registerBtn;
    private javax.swing.JButton resetBtn;
    private javax.swing.JTextField roleTxt;
    private javax.swing.JLabel s;
    private javax.swing.JPanel searchId;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
